[files]
extend-exclude = ["packages/ui/src/components/ui/mention-node.tsx", "packages/codegen/src/introspectionschema.json", "packages/codegen/src/schema.ts"]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-words = ["nda", "ndas", "NDA", "NDAs"]
extend-ignore-identifiers-re = ["(?i)nda[s]?"]
extend-ignore-words-re = ["(?i)requestor","(?i)indentity","(?i)encrypter","(?i)seeked","(?i)generater","(?i)policys", "typ", "vulnerabilitys", "(?i)ndas?"]
extend-ignore-re = ["(?Rm)^.*//\\s*spellchecker:disable-line$"]